In [1]:
# add vector
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(0, n):
    val = u[i] + v[i]
    w.append(val)
print(w)

[5, 7, 9]


In [2]:
import numpy as np

In [4]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

w = u + v
print(w)

[5 7 9]


In [5]:
w = u * v
print(w)

[ 4 10 18]


In [7]:
A = [[1, 5], [3, 4], [6, 2]]

number_of_rows = len(A)
number_of_columns = len(A[0])

At = []
for i in range(0, number_of_columns):
    rows = []
    for j in range(0, number_of_rows):
        rows.append(A[j][i])
    At.append(rows)

print(At)

[[1, 3, 6], [5, 4, 2]]


In [8]:
A = np.array([[1, 5], [3, 4], [6, 2]])
At = np.transpose(A)
print(At)

[[1 3 6]
 [5 4 2]]


In [9]:
A = np.array([[5, 2], [2, 1]])
At = np.transpose(A)
print(A == At)

[[ True  True]
 [ True  True]]
